# https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/get-started-with-kubernetes-monitoring
apiVersion: v1
kind: Secret
metadata:
  name: dynakube
  namespace: dynatrace
data:
  apiToken: dummy