---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: htpass-secret
  namespace: openshift-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: REPLACE
  target:
    name: htpass-secret-argo
    creationPolicy: Owner
  data:
    - secretKey: htpasswd
      remoteRef:
        key: REPLACE
