{{- $values := .Values -}}
{{- $bondName := .Values.bond.name -}}
{{- $releaseLabels := include "powerflex-configuration.labels" . -}}
{{- range $index, $node := $values.nodesBridge  }}
---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: {{ $index  }}-{{ $bondName }}-bridges
  labels:
    {{- $releaseLabels | nindent 4 }}
spec:
  {{- with $node.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  desiredState:
    interfaces:
    {{- range $values.interfaces }}
      - name: br{{ .id }}
        description: Linux bridge between {{ $bondName }}.{{ .id }} and br{{ .id }}
        type: {{ $node.type }}
        state: {{ $node.state }}
        {{- $ipAddress := get  $node.interfaceIDs  (.id | toString) }}
        ipv4:
          address:
          {{- toYaml $ipAddress | nindent 12 }}
          enabled: true
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: {{ $bondName }}.{{ .id }}
    {{- end }}
{{- end }}
