---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../bases/metallb-operator

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-50"

patches:
  - target:
      kind: Subscription
    patch: |-
      - op: replace
        path: /spec/channel
        value: "stable"
