---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: default-clusterset
  namespace: openshift-gitops
spec:
  clusterSets:
    - default
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: name
              operator: NotIn
              values:
                - local-cluster