---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../bases/dynatrace-operator

patches:
  - target:
      kind: Subscription
    patch: |-
      - op: replace
        path: /spec/channel
        value: "alpha"