---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: control-cluster-workloads-appset
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - git:
        repoURL: https://github.com/Vikaspogu/acm.git
        revision: main
        directories:
          - path: control-cluster/lab/workloads/*
  template:
    metadata:
      name: 'control-cluster-{{path.basename}}'
    spec:
      destination:
        server: "https://kubernetes.default.svc"
      project: default
      syncPolicy:
        automated: {}
        retry:
          limit: 10
          backoff:
            duration: "120s"
            factor: 5
            maxDuration: "10m0s"
      source:
        path: "{{path}}"
        repoURL: "https://github.com/Vikaspogu/acm.git"
        targetRevision: "main"
