---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openid-client-secret
  namespace: openshift-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: REPLACE
  target:
    name: openid-client-secret
    creationPolicy: Owner
  data:
    - secretKey: clientSecret
      remoteRef:
        key: REPLACE
