---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: clusters-appset
  namespace: openshift-gitops
  labels:
    {{- include "argo-application.labels" . | nindent 4 }}
spec:
  generators:
    - git:
        repoURL: https://github.com/Vikaspogu/acm.git
        revision: "main"
        directories:
          - path: kustomize/cluster-overlays/{{ .Values.clusterName }}/*
    - git:
        repoURL: https://github.com/Vikaspogu/acm.git
        revision: "main"
        directories:
          - path: helm/cluster-overlays/{{ .Values.clusterName }}/*
        template:
          metadata: {}
          spec:
            project: "default"
            source:
              repoURL: https://github.com/Vikaspogu/acm.git
              path: helm/charts/{{`{{.path.basename}}`}}
              helm:
                valueFiles:
                  - ../../cluster-overlays/{{ .Values.clusterName }}/{{`{{.path.basename}}`}}/values.yaml
            destination:
              server: "https://kubernetes.default.svc"
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: application-type
              operator: In
              values:
                - operator
        - matchExpressions:
            - key: application-type
              operator: In
              values:
                - configuration
        - matchExpressions:
            - key: application-type
              operator: NotIn
              values:
                - operator
                - configuration
  goTemplate: true
  template:
    metadata:
      name: '{{`{{.path.basename}}`}}'
      labels:
        application-type: '{{`{{ .path.basename | splitList "-" | last }}`}}'
    spec:
      destination:
        server: "https://kubernetes.default.svc"
      project: default
      syncPolicy:
        automated: {}
        retry:
          limit: 10
          backoff:
            duration: "120s"
            factor: 5
            maxDuration: "10m0s"
        syncOptions:
          - SkipDryRunOnMissingResource=true
          - Validate=false
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
      source:
        path: "{{.path.path}}"
        repoURL: "https://github.com/Vikaspogu/acm.git"
        targetRevision: main
