# Default values for nmstate.

bond:
  name: bond1
  mtu: 9000
  aggregation:
    mode: 802.3ad
    miimon: '100'
    ports:
      - eno3
      - eno4

interfaces:
  - id: 250
    mtu: 1500
    vlan:
      type: vlan
      state: up
    bridge:
      type: linux-bridge
      state: up
      ipAddresses:
        - ip: 10.216.205.206
          prefix-length: 24
  - id: 251
    mtu: 9000
    vlan:
      type: vlan
      state: up
    bridge:
      type: linux-bridge
      state: up
      ipAddresses:
        - ip: 10.216.251.206
          prefix-length: 24
  - id: 252
    mtu: 9000
    vlan:
      type: vlan
      state: up
    bridge:
      type: linux-bridge
      state: up
      ipAddresses:
        - ip: 10.216.252.206
          prefix-length: 24
  - id: 139
    mtu: 1500
    vlan:
      type: vlan
      state: up
    bridge:
      type: linux-bridge
      state: up
      ipAddresses:
        - ip: 10.216.139.206
          prefix-length: 24
  - id: 204
    mtu: 1500
    vlan:
      type: vlan
      state: up
    bridge:
      type: linux-bridge
      state: up
      ipAddresses:
        - ip: 10.216.204.206
          prefix-length: 24

nodeSelector: 
  node-role.kubernetes.io/worker: "true"
