kind: FalconNodeSensor
apiVersion: falcon.crowdstrike.com/v1alpha1
metadata:
  name: falcon-node-sensor
spec:
  falcon_api:
    client_id: PLEASE_FILL_IN
    client_secret: PLEASE_FILL_IN
    cloud_region: autodiscover
