---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: shared-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: git-url
      type: string
      description: url of the helm chart git repo
    - name: git-revision
      type: string
      description: revision to be used from repo of the helm chart
      default: master
    - description: The directory in source that contains the helm chart
      name: charts_dir
      type: string
    - description: The helm release version in semantic versioning format
      name: release_version
      type: string
    - description: The helm release name
      name: release_name
      type: string
    - default: ''
      description: The helm release namespace
      name: release_namespace
      type: string
    - description: >-
        Specify the values you want to overwrite, comma separated:
        autoscaling.enabled=true,replicas=1
      name: overwrite_values
      type: string
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: $(params.git-revision)
    - name: helm-install
      taskRef:
        name: helm-upgrade-from-source
        kind: ClusterTask
      params:
        - name: charts_dir
          value: $(params.charts_dir)
        - name: release_version
          value: $(params.release_version)
        - name: release_name
          value: $(params.release_name)
        - name: release_namespace
          value: $(params.release_namespace)
        - name: overwrite_values
          value: $(params.overwrite_values)
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - fetch-repository