---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../base/operators/acm

patches:
  - target:
      kind: Subscription
    patch: |-
      - op: replace
        path: /spec/channel
        value: "release-2.7"
