---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../bases/external-secret-store

patches:
  - target:
      kind: ClusterSecretStore
    patch: |-
      - op: replace
        path: /spec/provider/server
        value: "https://vault.com"
      - op: replace
        path: /spec/provider/vault/auth/tokenSecretRef/name
        value: "vault-token"
      - op: replace
        path: /spec/provider/vault/auth/tokenSecretRef/key
        value: "token"
